apiVersion: apps/v1
kind: Deployment
metadata:
  name: isbn-service-app
  labels:
    app: isbn-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isbn-service-app
  template:
    metadata:
      labels:
        app: isbn-service-app
    spec:
      containers:
        - name: isbn-service-app
          image: ecco18/isbn-service:v7
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  labels:
    monitor: isbn-service
  name: isbn-app-service
spec:
  selector:
    app: isbn-service-app
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: isbn-nodeport-service
spec:
  type: NodePort
  selector:
    app: isbn-service-app
  ports:
    - protocol: TCP
      nodePort: 30084
      port: 8083