apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: isbn-service-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      monitor: isbn-service
  endpoints:
    - port: api
      path: '/actuator/prometheus'
      interval: 30s
      honorLabels: true